#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : certbot
Version  : 0.10.2
Release  : 1
URL      : https://github.com/certbot/certbot/archive/v0.10.2.tar.gz
Source0  : https://github.com/certbot/certbot/archive/v0.10.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: certbot-bin
Requires: certbot-python
BuildRequires : ConfigArgParse-python
BuildRequires : acme
BuildRequires : acme-python
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : configobj-python
BuildRequires : enum34-python
BuildRequires : future-python
BuildRequires : ndg_httpsclient-python
BuildRequires : parsedatetime-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pyOpenSSL
BuildRequires : pyasn1-python
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pyrfc3339-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mock-python
BuildRequires : python3-dev
BuildRequires : pytz-python
BuildRequires : requests
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : zope.component-python
BuildRequires : zope.event-python
BuildRequires : zope.interface

%description
This directory contains your keys and certificates.
`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
without reading further documentation (see link below).

%package bin
Summary: bin components for the certbot package.
Group: Binaries

%description bin
bin components for the certbot package.


%package python
Summary: python components for the certbot package.
Group: Default

%description python
python components for the certbot package.


%prep
%setup -q -n certbot-0.10.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1485899303
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
export SOURCE_DATE_EPOCH=1485899303
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/certbot

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
